# Generated by Django 4.0.3 on 2022-03-10 05:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('access_level', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lowest'), (1, 'RESTRITED'), (2, 'CONFIDENTIAL'), (3, 'SECRET'), (4, 'TOP SECRET')], default=0, null=True)),
            ],
        ),
    ]
