# Generated by Django 4.0.3 on 2022-03-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211021_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name', 'email')},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lowest'), (1, 'RESTRITED'), (2, 'CONFIDENTIAL'), (3, 'SECRET'), (4, 'TOP_SECRET')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, ' General')], default=2, null=True),
        ),
    ]
