# Generated by Django 4.0.3 on 2022-03-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_rename_last_name_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lowest'), (1, 'RESTRITED'), (2, 'CONFIDENTIAL'), (3, 'SECRET'), (4, 'TOP SECRET')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='full name'),
        ),
    ]
