FROM python:3.8.10-alpine

ENV DATABASE_URL=postgresql://document_repo:document_repo@db:5432/document_repo \
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.1.13 \
  PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1

RUN pip install "poetry==$POETRY_VERSION"

WORKDIR /server

COPY poetry.lock pyproject.toml /server/

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY . /server/

COPY ./docker-entrypoint.sh /server/

RUN pwd
RUN ls -l

RUN chmod +x /server/docker-entrypoint.sh

ENTRYPOINT [ "/server/docker-entrypoint.sh" ]

EXPOSE 8000
